- name: Pull and run docker image
  hosts: localhost
  tasks:

    - name: removing old containers
      shell: docker ps -aq --filter name="spe-calculator" | xargs docker stop | xargs docker rm

    - name: pull image
      shell: docker pull gaganagarwal77/spe-calculator:latest
      
    - name: run container
      shell: docker run -i -t --name spe-calculator -d gaganagarwal77/spe-calculator
